applications:
  hubspot:
    component: hubspotWebHookIntegration
    name: HubSpot
    description: "Use this application to receive HubSpot notifications on your chat rooms."
    publisher: Symphony
    context: hubspot
    enable: true
    visible: true